### PR TITLE
Update to Ruby 2.4.0

### PR DESCRIPTION
**Pull request by aycabta**
...and fix some specs.

### CODE REVIEW

**Comment by raa0121** [comment]
テストこけるの、また`chichinai` での 403か…

**Comment by aycabta** [comment]
Nothing can be done about AWS's IP addresses are rejected.

**Comment by raa0121** [comment]
Travis でのテストの時にはスキップするようにできないですかね ＞`chichinai`

**Comment by supermomonga** [comment]
スキップするよりはモックを使う方が良いですね

**Comment by aycabta** [comment]
The tests of `lingrbot-means` are for what real responses sometimes change. I think logic test is weak reason for using webmock because creation of response HTML for webmock is too much work.

**Comment by aycabta** [comment]
I split off the tests issue to #52. Please review updating to Ruby 2.4.0.

**Comment by raa0121** [comment]
[LGTM](https://lgtm.in/i/kiQz0Uv0q)

**Comment by osyo-manga** [comment]
👍

**Comment by aycabta** [comment]
muscle

**Pull request merged**
